In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('dados_passagens_raw.csv')
df.head()

,compra_id,quantidade_assentos,posicoes_assentos,origem,destino,preco_unitario,data_partida
0,C-000395,3,"9A, 11A, 15B",São Paulo (Tietê),Salvador (BA),270.97,2024/07/13
1,C-000270,2,"18A, 17B",São Paulo (Tietê),Curitiba (PR),114.81,2024-06-23 07:30
2,C-000094,3,"19B, 17B, 3A",São Paulo (Tietê),Porto Alegre (RS),221.01,2024-10-01 23:45
3,C-000123,4,"16B, 17A, 9B, 3B",São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
4,C-000308,2,"5B, 10A",São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00

In [3]:
# Vamos começar o tratamento de correção de erros
# Vamos verificar os valores nulos por coluna

df.isnull().sum()

compra_id               0
quantidade_assentos     0
posicoes_assentos      31
origem                  0
destino                21
preco_unitario         29
data_partida           36
dtype: int64

In [4]:
df.describe(include='all')

,compra_id,quantidade_assentos,posicoes_assentos,origem,destino,preco_unitario,data_partida
count,511,511.000000,480,511,490,482.000000,475
unique,500,NaN,292,2,16,NaN,75
top,C-000365,NaN,15B,São Paulo (Tietê),Brasília (DF),NaN,2024-05-22 15:30
freq,2,NaN,10,508,68,NaN,18
mean,NaN,1.921722,NaN,NaN,NaN,248.444274,NaN
std,NaN,1.078187,NaN,NaN,NaN,660.905360,NaN
min,NaN,0.000000,NaN,NaN,NaN,-41.690000,NaN
25%,NaN,1.000000,NaN,NaN,NaN,121.570000,NaN
50%,NaN,2.000000,NaN,NaN,NaN,185.150000,NaN
75%,NaN,3.000000,NaN,NaN,NaN,270.985000,NaN
max,NaN,5.000000,NaN,NaN,NaN,9048.840000,NaN

In [5]:
# 1. Erros de digitação no destino

valores_unicos = df['destino'].unique()
valores_unicos

<StringArray>
[      'Salvador (BA)',       'Curitiba (PR)',   'Porto Alegre (RS)',
 'Rio de Janeiro (RJ)',      'Fortaleza (CE)',       'Brasília (DF)',
  'Florianópolis (SC)',         'Recife (PE)',       'Brasíli a(DF)',
        'Goiânia (GO)',       'brasília (df)', 'Belo Horizonte (MG)',
                   nan,    'Porto Alegre(RS)',   'Belo Horizonte MG',
       'Brasilia (DF)',       'Brasílai (DF)']
Length: 17, dtype: str

In [6]:
erros = ['Brasíli a(DF)', 'brasília (df)', 'Brasilia (DF)', 'Brasílai (DF)']
df['destino'] = df['destino'].replace(erros, 'Brasília (DF)')

df['destino'] = df['destino'].replace('Belo Horizonte MG', 'Belo Horizonte (MG)')

df['destino'] = df['destino'].replace('Porto Alegre(RS)', 'Porto Alegre (RS)')

valores_unicos = df['destino'].unique()
valores_unicos

<StringArray>
[      'Salvador (BA)',       'Curitiba (PR)',   'Porto Alegre (RS)',
 'Rio de Janeiro (RJ)',      'Fortaleza (CE)',       'Brasília (DF)',
  'Florianópolis (SC)',         'Recife (PE)',        'Goiânia (GO)',
 'Belo Horizonte (MG)',                   nan]
Length: 11, dtype: str

In [7]:
# 2. Erros de destino nulo

linhas_vazias = df[df['destino'].isna() | (df['destino'].astype(str).str.strip() == '')]
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None):
    display(linhas_vazias)

,compra_id,quantidade_assentos,posicoes_assentos,origem,destino,preco_unitario,data_partida
59,C-000172,2,"9A, 13B",São Paulo (Tietê),NaN,NaN,2024-05-05 11:00
71,C-000106,2,"12A, 10B",São Paulo (Tietê),NaN,185.15,2024-03-12 15:30
85,C-000481,2,"4B, 1A",São Paulo (Tietê),NaN,133.63,2024-01-04 15:30
86,C-000246,1,8A,São Paulo (Tietê),NaN,121.51,2024-04-29 22:30
100,C-000040,4,"7B, 11A, 8B, 9A",São Paulo (Tietê),NaN,-33.85,2024-04-27 11:00
113,C-000090,2,"3A, 16A",São Paulo (Tietê),NaN,152.81,2024-11-01 22:30
175,C-000355,3,"18B, 8B, 4A",São Paulo (Tietê),NaN,133.63,2024-01-04 15:30
178,C-000367,2,NaN,São Paulo (Tietê),NaN,NaN,NaN
200,C-000419,2,"15B, 14B",São Paulo (Tietê),NaN,114.81,2024-06-23 07:30
272,C-000284,2,"4B, 3B",São Paulo (Tietê),NaN,322.95,2024-03-24 15:30
277,C-000253,1,11B,São Paulo (Tietê),NaN,342.57,2024-01-17 23:45
305,C-000408,1,15A,São Paulo (Tietê),NaN,112.85,2024-04-24 18:00
331,C-000148,1,18A,São Paulo (Tietê),NaN,211.83,2024-07-12 07:30
343,C-000095,4,"6A, 18A, 6B, 20A",São Paulo (Tietê),NaN,307.78,2024-05-22 15:30
359,C-000161,3,"13B, 15B, 11A",São Paulo (Tietê),NaN,270.99,2024-04-29 15:30
385,C-000447,3,"11A, 4B, 5A",São Paulo (Tietê),NaN,155.36,2024-03-22 18:00
432,C-000271,2,"16B, 14B",São Paulo (Tietê),NaN,338.27,2024-06-10 15:30
440,C-000136,1,18A,São Paulo (Tietê),NaN,185.15,2024-03-12 15:30
470,C-000198,1,18B,São Paulo (Tietê),NaN,317.82,17/05/2024
487,C-000455,2,"7B, 12B",São Paulo (Tietê),NaN,173.40,2024-01-06 07:30
494,C-000225,2,"10B, 5A",São Paulo (Tietê),NaN,270.99,2024-04-29 15:30

In [8]:
# Preenche os NaNs da coluna 'destino' usando um destino válido que coincide com 'data_partida'

df['destino'] = df['destino'].fillna(df.groupby('data_partida')['destino'].transform('first'))
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None):
    display(df)

,compra_id,quantidade_assentos,posicoes_assentos,origem,destino,preco_unitario,data_partida
0,C-000395,3,"9A, 11A, 15B",São Paulo (Tietê),Salvador (BA),270.97,2024/07/13
1,C-000270,2,"18A, 17B",São Paulo (Tietê),Curitiba (PR),114.81,2024-06-23 07:30
2,C-000094,3,"19B, 17B, 3A",São Paulo (Tietê),Porto Alegre (RS),221.01,2024-10-01 23:45
3,C-000123,4,"16B, 17A, 9B, 3B",São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
4,C-000308,2,"5B, 10A",São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
5,C-000365,2,"10B, 21B",São Paulo (Tietê),Rio de Janeiro (RJ),97.45,2024-01-13 22:30
6,C-000208,4,"20A, 21B, 2A, 3A",São Paulo (Tietê),Brasília (DF),185.15,2024-03-12 15:30
7,C-000359,2,"21B, 18A",São Paulo (Tietê),Curitiba (PR),108.82,2024-04-20 23:45
8,C-000068,1,3A,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
9,C-000451,3,"12A, 10A, 3B",São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
10,C-000092,1,5B,São Paulo (Tietê),Florianópolis (SC),172.06,2024-12-14 13:00
11,C-000086,2,"6A, 3B",São Paulo (Tietê),Florianópolis (SC),NaN,2024-12-15 09:00
12,C-000131,2,"18A, 16A",São Paulo (Tietê),Recife (PE),332.34,2024-11-07 20:00
13,C-000020,2,"2B, 21B",São Paulo (Tietê),Brasília (DF),169.85,2024-05-14 20:00
14,C-000283,2,"7B, 14B",São Paulo (Tietê),Brasília (DF),189.18,2024-10-26 07:30
15,C-000421,1,15A,São Paulo (Tietê),Curitiba (PR),108.82,2024-04-20 23:45
16,C-000295,1,14B,São Paulo (Tietê),Goiânia (GO),173.97,2024-03-19 07:30
17,C-000164,1,3A,São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
18,C-000247,4,"16B, 3B, 7B, 1B",São Paulo (Tietê),Curitiba (PR),121.57,2024-08-04 18:00
19,C-000453,1,15B,São Paulo (Tietê),Fortaleza (CE),350.00,2024-04-27 11:00
20,C-000401,4,"4A, 7B, 20B, 13B",São Paulo (Tietê),Brasília (DF),153.55,2024-05-06 11:00
21,C-000417,4,"12B, 6B, 2A, 6A",São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
22,C-000439,2,"8B, 7B",São Paulo (Tietê),Brasília (DF),184.86,2024-10-14 09:00
23,C-000327,1,16A,São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
24,C-000166,1,8B,São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
25,C-000399,1,3A,São Paulo (Tietê),Recife (PE),301.69,2024-11-21 18:00
26,C-000228,2,"7A, 8A",São Paulo (Tietê),Fortaleza (CE),342.57,2024-01-17 23:45
27,C-000111,1,13B,São Paulo (Tietê),Florianópolis (SC),195.42,2024-11-24 13:00
28,C-000215,1,4A,São Paulo (Tietê),Porto Alegre (RS),198.63,2024-03-04 11:00
29,C-000015,1,8B,São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
30,C-000240,1,7B,São Paulo (Tietê),Curitiba (PR),104.13,2024-12-23 07:30
31,C-000146,5,"19B, 12B, 13A, 16B, 10B",São Paulo (Tietê),Brasília (DF),195.46,2024-08-07 06:00
32,C-000072,2,"9A, 2A",São Paulo (Tietê),Porto Alegre (RS),221.01,2024-10-01 23:45
33,C-000450,2,"2A, 4B",São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
34,C-000112,1,15B,São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
35,C-000115,1,13B,São Paulo (Tietê),Fortaleza (CE),342.57,2024-01-17 23:45
36,C-000432,1,16A,São Paulo (Tietê),Brasília (DF),0.00,2024-10-02 22:30
37,C-000304,1,12A,São Paulo (Tietê),Florianópolis (SC),205.05,NaN
38,C-000446,1,13A,São Paulo (Tietê),Recife (PE),323.13,2024-03-28 13:00
39,C-000237,2,"19B, 14A",São Paulo (Tietê),Salvador (BA),270.99,2024-04-29 15:30
40,C-000223,1,20A,São Paulo (Tietê),Brasília (DF),184.86,2024-10-14 09:00
41,C-000333,1,17A,São Paulo (Tietê),Florianópolis (SC),205.05,2024-05-16 06:00
42,C-000487,1,NaN,São Paulo (Tietê),Florianópolis (SC),172.06,2024-12-14 13:00
43,C-000231,2,"12A, 4B",São Paulo (Tietê),Recife (PE),290.60,2024-09-30 22:30
44,C-000153,1,2B,São Paulo (Tietê),Curitiba (PR),114.81,2024-06-23 07:30
45,C-000217,1,10A,São Paulo (Tietê),Curitiba (PR),116.38,2024-03-20 15:30
46,C-000085,1,7B,São Paulo (Tietê),Goiânia (GO),147.41,2024-11-17 18:00
47,C-000389,2,"12B, 16B",São Paulo (Tietê),Porto Alegre (RS),216.61,2024-08-23 15:30
48,C-000078,2,"4B, 11A",São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
49,C-000203,4,"5A, 19B, 13A, 4A",São Paulo (Tietê),Florianópolis (SC),172.06,NaN
50,C-000235,3,"9A, 3B, 16A",São Paulo (Tietê),Brasília (DF),NaN,2024-03-12 15:30
51,C-000488,1,13A,São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-03-12 06:00
52,C-000383,2,"8A, 21B",São Paulo (Tietê),Florianópolis (SC),172.06,NaN
53,C-000182,2,"11A, 9A",São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-03-12 06:00
54,C-000469,2,"16B, 11A",São Paulo (Tietê),Porto Alegre (RS),202.74,NaN
55,C-000379,1,2B,São Paulo (Tietê),Porto Alegre (RS),NaN,2024-07-12 07:30
56,C-000294,1,21B,São Paulo (Tietê),Fortaleza (CE),342.57,2024-01-17 23:45
57,C-000047,2,"19B, 1B",São Paulo (Tietê),Recife (PE),300.08,2024-05-05 11:00
58,C-000445,2,"5B, 12B",São Paulo (Tietê),Belo Horizonte (MG),133.69,NaN
59,C-000172,2,"9A, 13B",São Paulo (Tietê),Recife (PE),NaN,2024-05-05 11:00
60,C-000475,2,"7B, 7A",São Paulo (Tietê),Salvador (BA),279.80,2024-08-20 11:00
61,C-000254,1,11A,São Paulo (Tietê),Belo Horizonte (MG),133.69,2024-04-21 11:00
62,C-000477,1,9A,São Paulo (Tietê),Recife (PE),332.34,2024-11-07 20:00
63,C-000079,1,15B,São Paulo (Tietê),Florianópolis (SC),202.19,2024-02-28 18:00
64,C-000008,2,"20A, 14B",São Paulo (Tietê),Salvador (BA),264.13,2024-11-21 13:00
65,C-000027,4,"8B, 6A, 14A, 16B",São Paulo (Tietê),Rio de Janeiro (RJ),87.93,2024-05-20 07:30
66,C-000019,2,"12A, 14B",São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
67,C-000193,5,"8B, 16A, 19A, 5B, 13A",São Paulo (Tietê),Florianópolis (SC),187.22,2024-10-10 15:30
68,C-000189,2,"12B, 20B",São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
69,C-000222,2,"11A, 1B",São Paulo (Tietê),Fortaleza (CE),329.20,2024-02-03 18:00
70,C-000138,3,"12A, 10A, 20B",São Paulo (Tietê),Fortaleza (CE),329.20,2024-02-03 18:00
71,C-000106,2,"12A, 10B",São Paulo (Tietê),Brasília (DF),185.15,2024-03-12 15:30
72,C-000433,2,"9A, 6B",São Paulo (Tietê),Florianópolis (SC),210.34,2024-12-15 09:00
73,C-000255,1,3B,São Paulo (Tietê),Florianópolis (SC),205.05,2024-05-16 06:00
74,C-000393,3,"7B, 2A, 7A",São Paulo (Tietê),Florianópolis (SC),210.34,2024-12-15 09:00
75,C-000018,3,"14A, 7A, 4A",São Paulo (Tietê),Salvador (BA),307.78,2024-05-22 15:30
76,C-000016,2,"7B, 18A",São Paulo (Tietê),Recife (PE),301.69,2024-11-21 18:00
77,C-000310,2,"4A, 7B",São Paulo (Tietê),Porto Alegre (RS),-36.85,2024-10-01 23:45
78,C-000324,2,"13B, 11A",São Paulo (Tietê),Florianópolis (SC),188.92,2024-10-01 20:00
79,C-000466,5,"11A, 12A, 9A, 6B, 3B",São Paulo (Tietê),Fortaleza (CE),342.57,2024-01-17 23:45
80,C-000344,1,17A,São Paulo (Tietê),Porto Alegre (RS),211.83,2024-07-12 07:30
81,C-000185,1,13A,São Paulo (Tietê),Brasília (DF),169.85,2024-05-14 20:00
82,C-000414,3,"5B, 11B, 13A",São Paulo (Tietê),Porto Alegre (RS),198.63,2024-03-04 11:00
83,C-000212,1,19A,São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
84,C-000233,3,"1A, 10B, 20B",São Paulo (Tietê),Belo Horizonte (MG),103.01,NaN
85,C-000481,2,"4B, 1A",São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
86,C-000246,1,8A,São Paulo (Tietê),Belo Horizonte (MG),121.51,2024-04-29 22:30
87,C-000242,2,"6A, 15B",São Paulo (Tietê),Brasília (DF),189.18,2024-10-26 07:30
88,C-000499,3,"7B, 6B, 14A",São Paulo (Tietê),Goiânia (GO),155.36,2024-03-22 18:00
89,C-000293,3,"16B, 6A, 6B",São Paulo (Tietê),Porto Alegre (RS),225.64,2024-05-30 13:00
90,C-000209,2,"13A, 10A",São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
91,C-000467,4,"14B, 15A, 11B, 21A",São Paulo (Tietê),Goiânia (GO),164.97,2024-12-14 23:45
92,C-000158,2,"2B, 6B",São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
93,C-000474,1,12A,São Paulo (Tietê),Belo Horizonte (MG),103.05,2024-01-14 20:00
94,C-000118,5,"12A, 8A, 21B, 3A, 2A",São Paulo (Tietê),Belo Horizonte (MG),133.69,2024-04-21 11:00
95,C-000322,2,NaN,São Paulo (Tietê),Belo Horizonte (MG),103.05,2024-01-14 20:00
96,C-000033,4,"21A, 19B, 2B, 12A",São Paulo (Tietê),Porto Alegre (RS),225.64,2024-05-30 13:00
97,C-000194,4,"17B, 5A, 3A, 9B",São Paulo (Tietê),Porto Alegre (RS),211.83,2024-07-12 07:30
98,C-000076,1,19A,São Paulo (Tietê),Goiânia (GO),173.97,2024-03-19 07:30
99,C-000025,1,NaN,São Paulo (Tietê),Belo Horizonte (MG),118.14,2024-11-04 11:00
100,C-000040,4,"7B, 11A, 8B, 9A",São Paulo (Tietê),Fortaleza (CE),-33.85,2024-04-27 11:00
101,C-000330,1,17B,São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
102,C-000066,0,8A,São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
103,C-000404,2,"3B, 13A",São Paulo (Tietê),Fortaleza (CE),350.00,2024-04-27 11:00
104,C-000276,1,10B,São Paulo (Tietê),Brasília (DF),195.86,2024-05-15 18:00
105,C-000326,3,NaN,São Paulo (Tietê),Belo Horizonte (MG),133.69,2024-04-21 11:00
106,C-000303,1,16B,São Paulo (Tietê),Curitiba (PR),101.30,2024-03-22 07:30
107,C-000074,2,NaN,São Paulo (Tietê),Goiânia (GO),173.97,2024-03-19 07:30
108,C-000346,1,7A,São Paulo (Tietê),Florianópolis (SC),205.05,2024-05-16 06:00
109,C-000102,2,"8B, 3B",São Paulo (Tietê),Brasília (DF),153.55,2024-05-06 11:00
110,C-000291,1,18B,São Paulo (Tietê),Salvador (BA),270.99,2024-04-29 15:30
111,C-000409,2,"14A, 5A",São Paulo (Tietê),Brasília (DF),195.86,2024-05-15 18:00
112,C-000133,1,8B,São Paulo (Tietê),Recife (PE),332.34,2024-11-07 20:00
113,C-000090,2,"3A, 16A",São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
114,C-000280,4,"13A, 1A, 7B, 6B",São Paulo (Tietê),Recife (PE),322.95,2024-03-24 15:30
115,C-000496,2,"8A, 7B",São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
116,C-000341,2,"9A, 16B",São Paulo (Tietê),Brasília (DF),173.09,2024-03-14 23:45
117,C-000472,3,"14A, 13B, 5A",São Paulo (Tietê),Brasília (DF),185.15,2024-03-12 15:30
118,C-000177,2,"9B, 6B",São Paulo (Tietê),Florianópolis (SC),188.92,NaN
119,C-000312,1,3A,São Paulo (Tietê),Fortaleza (CE),350.00,2024-04-27 11:00
120,C-000360,3,"6A, 9A, 3A",São Paulo (Tietê),Curitiba (PR),104.13,2024-12-23 07:30
121,C-000009,4,"7A, 10B, 13B, 21B",São Paulo (Tietê),Porto Alegre (RS),225.64,2024-05-30 13:00
122,C-000211,1,13B,São Paulo (Tietê),Curitiba (PR),NaN,2024-01-04 15:30
123,C-000150,2,"12B, 4B",São Paulo (Tietê),Recife (PE),301.69,2024-11-21 18:00
124,C-000380,1,18B,São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
125,C-000105,1,1B,São Paulo (Tietê),Brasília (DF),189.18,2024-10-26 07:30
126,C-000249,3,"21B, 8B, 9A",São Paulo (Tietê),Belo Horizonte (MG),102.96,2024-09-15 18:00
127,C-000054,1,16B,São Paulo (Tietê),Salvador (BA),264.13,2024-11-21 13:00
128,C-000070,2,"18B, 12A",São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
129,C-000278,2,"16A, 20A",São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
130,C-000410,1,18A,São Paulo (Tietê),Belo Horizonte (MG),103.01,2024-10-14 23:45
131,C-000077,1,3A,São Paulo (Tietê),Porto Alegre (RS),221.66,2024-02-10 06:00
132,C-000201,1,17B,São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-02-22 06:00
133,C-000429,1,15B,São Paulo (Tietê),Goiânia (GO),174.63,2024-08-04 20:00
134,C-000352,4,"19A, 2B, 18A, 16B",São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
135,C-000266,1,5A,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
136,C-000299,3,"19A, 17B, 18A",São Paulo (Tietê),Belo Horizonte (MG),118.14,2024-11-04 11:00
137,C-000199,2,"11B, 7A",São Paulo (Tietê),Brasília (DF),NaN,2024-03-12 15:30
138,C-000101,1,9A,São Paulo (Tietê),Belo Horizonte (MG),103.05,2024-01-14 20:00
139,C-000323,2,"11A, 13A",São Paulo (Tietê),Salvador (BA),307.78,2024-05-22 15:30
140,C-000249,3,"21B, 8B, 9A",São Paulo (Tietê),Belo Horizonte (MG),NaN,2024-09-15 18:00
141,C-000279,1,10A,São Paulo (Tietê),Recife (PE),332.34,2024-11-07 20:00
142,C-000213,1,13B,São Paulo (Tietê),Belo Horizonte (MG),121.51,2024-04-29 22:30
143,C-000056,2,"13A, 20A",São Paulo (Tietê),Curitiba (PR),93.82,2024-04-20 23:45
144,C-000268,4,"17A, 3A, 3B, 15B",São Paulo (Tietê),Brasília (DF),195.86,2024-05-15 18:00
145,C-000055,2,"4B, 3A",São Paulo (Tietê),Brasília (DF),195.46,2024-08-07 06:00
146,C-000250,3,"21B, 1A, 10B",São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
147,C-000494,1,21A,São Paulo (Tietê),Porto Alegre (RS),211.83,2024-07-12 07:30
148,C-000486,4,"6B, 17A, 2A, 16B",São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-03-12 06:00
149,C-000216,2,NaN,São Paulo (Tietê),Brasília (DF),185.15,2024-03-12 15:30
150,C-000072,2,"9A, 2A",São Paulo (Tietê),Porto Alegre (RS),221.01,2024-10-01 23:45
151,C-000319,4,"21A, 7A, 12A, 18A",São Paulo (Tietê),Goiânia (GO),NaN,2024-03-22 18:00
152,C-000281,1,NaN,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
153,C-000024,1,8B,São Paulo (Tietê),Porto Alegre (RS),NaN,2024-03-04 11:00
154,C-000300,1,1B,São Paulo (Tietê),Recife (PE),290.60,2024-09-30 22:30
155,C-000230,1,16A,São Paulo (Tietê),Porto Alegre (RS),216.61,2024-08-23 15:30
156,C-000022,1,7A,São Paulo (Tietê),Curitiba (PR),101.30,2024-03-22 07:30
157,C-000214,1,15B,São Paulo (Tietê),Goiânia (GO),173.97,2024-03-19 07:30
158,C-000196,3,"10B, 11A, 21A",São Paulo (Tietê),Recife (PE),332.34,2024-11-07 20:00
159,C-000325,1,8A,São Paulo (Tietê),Brasília (DF),153.55,2024-05-06 11:00
160,C-000110,2,NaN,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
161,C-000452,1,NaN,São Paulo (Tietê),Florianópolis (SC),210.34,2024-12-15 09:00
162,C-000122,3,"6B, 12A, 4B",São Paulo (Tietê),Curitiba (PR),104.13,2024-12-23 07:30
163,C-000482,1,17A,São Paulo (Tietê),Porto Alegre (RS),241.98,NaN
164,C-000443,1,11B,São Paulo (Tietê),Curitiba (PR),101.30,2024-03-22 07:30
165,C-000143,1,14B,São Paulo (Tietê),Belo Horizonte (MG),103.01,2024-10-14 23:45
166,C-000220,5,"11A, 15A, 9B, 16A, 7A",São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
167,C-000206,2,"9B, 12B",São Paulo (Tietê),Belo Horizonte (MG),118.14,2024-11-04 11:00
168,C-000437,1,4B,São Paulo (Tietê),Fortaleza (CE),350.00,2024-04-27 11:00
169,C-000473,1,NaN,São Paulo (Tietê),Recife (PE),290.60,2024-09-30 22:30
170,C-000302,3,"14A, 4B, 16B",São Paulo (Tietê),Goiânia (GO),164.97,2024-12-14 23:45
171,C-000305,1,6A,São Paulo (Tietê),Fortaleza (CE),335.48,2024-07-24 11:00
172,C-000264,3,"11B, 19B, 20A",São Paulo (Tietê),Curitiba (PR),104.13,2024-12-23 07:30
173,C-000021,1,11B,São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
174,C-000460,2,"16A, 7B",São Paulo (Tietê),Florianópolis (SC),205.05,2024-05-16 06:00
175,C-000355,3,"18B, 8B, 4A",São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
176,C-000002,3,NaN,São Paulo (Tietê),Recife (PE),300.08,2024-05-05 11:00
177,C-000407,1,11B,São Paulo (Tietê),Curitiba (PR),134.71,2024-05-22 15:30
178,C-000367,2,NaN,São Paulo (Tietê),NaN,NaN,NaN
179,C-000274,1,18B,São Paulo (Tietê),Porto Alegre (RS),225.64,2024-05-30 13:00
180,C-000117,1,19B,São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
181,C-000336,4,"17A, 7B, 8B, 5A",São Paulo (Tietê),Fortaleza (CE),335.48,2024-07-24 11:00
182,C-000221,3,"5A, 11B, 16B",São Paulo (Tietê),Brasília (DF),153.55,2024-05-06 11:00
183,C-000135,3,"14B, 15A, 16A",São Paulo (Tietê),Salvador (BA),307.78,2024-05-22 15:30
184,C-000043,2,"19A, 4A",São Paulo (Tietê),Goiânia (GO),164.97,2024-12-14 23:45
185,C-000071,1,9A,São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
186,C-000403,3,"19B, 8A, 4B",São Paulo (Tietê),Curitiba (PR),134.71,2024-05-22 15:30
187,C-000145,2,NaN,São Paulo (Tietê),Brasília (DF),195.86,2024-05-15 18:00
188,C-000370,1,1B,São Paulo (Tietê),Brasília (DF),195.86,2024-05-15 18:00
189,C-000413,1,21A,São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
190,C-000088,2,"8A, 7A",São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
191,C-000347,3,NaN,São Paulo (Tietê),Porto Alegre (RS),221.66,2024-02-10 06:00
192,C-000234,2,"9A, 20B",são paulo (tietê),Curitiba (PR),121.57,2024-08-04 18:00
193,C-000039,2,"19A, 17B",São Paulo (Tietê),Brasília (DF),189.18,2024-10-26 07:30
194,C-000165,1,15A,São Paulo (Tietê),Porto Alegre (RS),241.98,2024-01-23 23:45
195,C-000362,1,20B,São Paulo (Tietê),Goiânia (GO),164.97,2024-12-14 23:45
196,C-000120,2,"5A, 8A",São Paulo (Tietê),Curitiba (PR),114.81,2024-06-23 07:30
197,C-000337,1,5A,São Paulo (Tietê),Curitiba (PR),108.82,2024-04-20 23:45
198,C-000034,1,17A,São Paulo (Tietê),Belo Horizonte (MG),121.51,2024-04-29 22:30
199,C-000464,1,20B,São Paulo (Tietê),Porto Alegre (RS),202.74,NaN
200,C-000419,2,"15B, 14B",São Paulo (Tietê),Curitiba (PR),114.81,2024-06-23 07:30
201,C-000375,0,8B,São Paulo (Tietê),Recife (PE),290.60,2024-09-30 22:30
202,C-000471,1,16A,São Paulo (Tietê),Recife (PE),301.69,NaN
203,C-000169,2,"10A, 5B",São Paulo (Tietê),Salvador (BA),270.99,2024-04-29 15:30
204,C-000045,4,"3A, 8B, 12B, 10A",São Paulo (Tietê),Curitiba (PR),114.81,23/06/2024
205,C-000152,1,21B,São Paulo (Tietê),Porto Alegre (RS),221.01,2024-10-01 23:45
206,C-000432,1,16A,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
207,C-000396,2,"18A, 14B",São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-03-12 06:00
208,C-000476,1,21B,São Paulo (Tietê),Florianópolis (SC),195.42,2024-11-24 13:00
209,C-000003,1,6A,São Paulo (Tietê),Curitiba (PR),108.82,NaN
210,C-000200,2,"9B, 16B",São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
211,C-000387,1,7B,São Paulo (Tietê),Belo Horizonte (MG),103.05,2024-01-14 20:00
212,C-000252,1,7A,São Paulo (Tietê),Curitiba (PR),114.81,NaN
213,C-000098,3,"12B, 21A, 11B",São Paulo (Tietê),Salvador (BA),307.78,2024-05-22 15:30
214,C-000232,4,"7A, 10A, 16A, 15A",São Paulo (Tietê),Goiânia (GO),174.63,NaN
215,C-000424,2,"18B, 14B",São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
216,C-000087,2,"12B, 3B",São Paulo (Tietê),Recife (PE),323.13,NaN
217,C-000434,1,11B,São Paulo (Tietê),Goiânia (GO),174.63,2024-08-04 20:00
218,C-000272,3,"3B, 12A, 13B",São Paulo (Tietê),Brasília (DF),195.46,2024-08-07 06:00
219,C-000258,4,"2A, 14B, 20B, 1B",São Paulo (Tietê),Salvador (BA),270.99,2024-04-29 15:30
220,C-000405,3,"19A, 17B, 7B",São Paulo (Tietê),Recife (PE),300.08,2024-05-05 11:00
221,C-000314,2,"8B, 12A",São Paulo (Tietê),Recife (PE),301.69,2024-11-21 18:00
222,C-000385,1,15A,São Paulo (Tietê),Brasília (DF),-41.69,2024-08-07 06:00
223,C-000026,1,19B,São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
224,C-000461,1,4B,São Paulo (Tietê),Salvador (BA),NaN,2024-05-22 15:30
225,C-000064,1,2A,São Paulo (Tietê),Curitiba (PR),101.30,2024-03-22 07:30
226,C-000179,1,12B,São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
227,C-000416,1,8B,São Paulo (Tietê),Porto Alegre (RS),216.61,2024-08-23 15:30
228,C-000239,1,NaN,São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-03-12 06:00
229,C-000340,2,"2A, 14A",São Paulo (Tietê),Porto Alegre (RS),216.61,2024-08-23 15:30
230,C-000134,1,NaN,São Paulo (Tietê),Belo Horizonte (MG),NaN,2024-10-14 23:45
231,C-000256,1,14A,São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
232,C-000285,1,2B,São Paulo (Tietê),Curitiba (PR),108.82,2024-04-20 23:45
233,C-000465,3,"3B, 6A, 9A",São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
234,C-000053,1,5A,São Paulo (Tietê),Rio de Janeiro (RJ),97.45,2024-01-13 22:30
235,C-000028,1,13B,São Paulo (Tietê),Florianópolis (SC),187.22,2024-10-10 15:30
236,C-000335,1,11A,São Paulo (Tietê),Recife (PE),322.95,2024-03-24 15:30
237,C-000005,4,"10B, 8B, 2B, 19A",São Paulo (Tietê),Curitiba (PR),104.13,2024-12-23 07:30
238,C-000296,2,"18A, 19B",São Paulo (Tietê),Florianópolis (SC),195.42,2024-11-24 13:00
239,C-000126,1,14B,São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-02-22 06:00
240,C-000384,1,3B,São Paulo (Tietê),Florianópolis (SC),188.92,01/10/2024
241,C-000493,2,"19A, 7B",São Paulo (Tietê),Rio de Janeiro (RJ),87.93,2024-05-20 07:30
242,C-000142,1,1B,São Paulo (Tietê),Florianópolis (SC),173.40,2024-01-06 07:30
243,C-000149,1,16B,São Paulo (Tietê),Porto Alegre (RS),198.63,2024-03-04 11:00
244,C-000265,1,18B,São Paulo (Tietê),Salvador (BA),275.62,2024-02-21 09:00
245,C-000462,1,13B,São Paulo (Tietê),Porto Alegre (RS),211.83,2024-07-12 07:30
246,C-000364,2,"6B, 10B",São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
247,C-000084,3,"21B, 11B, 16A",São Paulo (Tietê),Goiânia (GO),NaN,2024-03-19 07:30
248,C-000061,5,"6A, 9A, 6B, 7A, 14B",São Paulo (Tietê),Brasília (DF),NaN,2024-05-14 20:00

In [9]:
# Verificando quantos destinos nulos ainda existem para preenhcer os restantes

linhas_vazias = df[df['destino'].isna() | (df['destino'].astype(str).str.strip() == '')]
with pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.max_colwidth', None):
    display(linhas_vazias)

,compra_id,quantidade_assentos,posicoes_assentos,origem,destino,preco_unitario,data_partida
178,C-000367,2,NaN,São Paulo (Tietê),NaN,NaN,NaN
470,C-000198,1,18B,São Paulo (Tietê),NaN,317.82,17/05/2024

In [10]:
# Como a linha 178 está praticamente toda nula, vamos dropá-la. Já a linha 470, pelo valor e data, podemos preencher com o destino correto, que é "Fortaleza (CE)" e aproveitar para corrigir a data para "2024-05-17 20:00".

df.loc[470, ['destino', 'data_partida']] = ['Fortaleza (CE)', '2024-05-17 20:00']
display(df.loc[[470]])

,compra_id,quantidade_assentos,posicoes_assentos,origem,destino,preco_unitario,data_partida
470,C-000198,1,18B,São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00

In [11]:
# 3. Erros de preco_unitario

linhas_vazias = df[
    df['preco_unitario'].isna() | 
    (df['preco_unitario'] <= 0) | 
    (df['preco_unitario'] > 400)
]
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(linhas_vazias)

,compra_id,quantidade_assentos,posicoes_assentos,origem,destino,preco_unitario,data_partida
11,C-000086,2,"6A, 3B",São Paulo (Tietê),Florianópolis (SC),NaN,2024-12-15 09:00
36,C-000432,1,16A,São Paulo (Tietê),Brasília (DF),0.00,2024-10-02 22:30
50,C-000235,3,"9A, 3B, 16A",São Paulo (Tietê),Brasília (DF),NaN,2024-03-12 15:30
55,C-000379,1,2B,São Paulo (Tietê),Porto Alegre (RS),NaN,2024-07-12 07:30
59,C-000172,2,"9A, 13B",São Paulo (Tietê),Recife (PE),NaN,2024-05-05 11:00
77,C-000310,2,"4A, 7B",São Paulo (Tietê),Porto Alegre (RS),-36.85,2024-10-01 23:45
100,C-000040,4,"7B, 11A, 8B, 9A",São Paulo (Tietê),Fortaleza (CE),-33.85,2024-04-27 11:00
122,C-000211,1,13B,São Paulo (Tietê),Curitiba (PR),NaN,2024-01-04 15:30
137,C-000199,2,"11B, 7A",São Paulo (Tietê),Brasília (DF),NaN,2024-03-12 15:30
140,C-000249,3,"21B, 8B, 9A",São Paulo (Tietê),Belo Horizonte (MG),NaN,2024-09-15 18:00
151,C-000319,4,"21A, 7A, 12A, 18A",São Paulo (Tietê),Goiânia (GO),NaN,2024-03-22 18:00
153,C-000024,1,8B,São Paulo (Tietê),Porto Alegre (RS),NaN,2024-03-04 11:00
178,C-000367,2,NaN,São Paulo (Tietê),NaN,NaN,NaN
222,C-000385,1,15A,São Paulo (Tietê),Brasília (DF),-41.69,2024-08-07 06:00
224,C-000461,1,4B,São Paulo (Tietê),Salvador (BA),NaN,2024-05-22 15:30
230,C-000134,1,NaN,São Paulo (Tietê),Belo Horizonte (MG),NaN,2024-10-14 23:45
247,C-000084,3,"21B, 11B, 16A",São Paulo (Tietê),Goiânia (GO),NaN,2024-03-19 07:30
248,C-000061,5,"6A, 9A, 6B, 7A, 14B",São Paulo (Tietê),Brasília (DF),NaN,2024-05-14 20:00
288,C-000321,0,13B,São Paulo (Tietê),Goiânia (GO),NaN,2024-03-22 18:00
291,C-000441,2,"18B, 20A",São Paulo (Tietê),Florianópolis (SC),NaN,2024-12-14 13:00
293,C-000383,2,"8A, 21B",São Paulo (Tietê),Florianópolis (SC),NaN,2024-12-14 13:00
295,C-000049,2,"5B, 10A",São Paulo (Tietê),Curitiba (PR),NaN,2024-03-22 07:30
301,C-000366,1,14A,São Paulo (Tietê),Brasília (DF),8324.68,2024-10-26 07:30
320,C-000331,2,"3B, 11B",São Paulo (Tietê),Curitiba (PR),660.37,2024-06-23 07:30
344,C-000082,2,"11B, 14B",São Paulo (Tietê),Porto Alegre (RS),NaN,2024-10-01 23:45
346,C-000219,4,"19B, 6B, 3A, 16B",São Paulo (Tietê),Goiânia (GO),NaN,2024-08-04 20:00
360,C-000358,1,10A,São Paulo (Tietê),Belo Horizonte (MG),NaN,2024-01-14 20:00
371,C-000267,1,10B,São Paulo (Tietê),Fortaleza (CE),8171.06,2024-04-27 11:00
377,C-000078,2,"4B, 11A",São Paulo (Tietê),Fortaleza (CE),NaN,2024-06-10 15:30
389,C-000412,5,"4A, 17A, 20B, 13B, 12A",São Paulo (Tietê),Curitiba (PR),NaN,2024-06-23 07:30
397,C-000210,1,4B,São Paulo (Tietê),Belo Horizonte (MG),NaN,2024-10-14 23:45
404,C-000044,2,"17A, 9A",São Paulo (Tietê),Belo Horizonte (MG),NaN,2024-11-04 11:00
407,C-000140,1,15B,São Paulo (Tietê),Belo Horizonte (MG),NaN,2024-01-14 20:00
409,C-000041,1,21B,São Paulo (Tietê),Brasília (DF),NaN,2024-10-14 09:00
414,C-000006,1,16B,São Paulo (Tietê),Belo Horizonte (MG),NaN,2024-01-14 20:00
443,C-000262,1,14A,São Paulo (Tietê),Fortaleza (CE),NaN,2024-01-17 23:45
504,C-000371,3,"15A, 10B, 5A",São Paulo (Tietê),Fortaleza (CE),9048.84,2024-02-03 18:00

In [12]:
# Converter os valores discrepantes para NaN e trocar para o valor válido com mesmo 'destino' e 'data_partida'

df.loc[(df['preco_unitario'] <= 0) | (df['preco_unitario'] > 400), 'preco_unitario'] = np.nan

df['preco_unitario'] = df['preco_unitario'].fillna(
    df.groupby(['destino', 'data_partida'])['preco_unitario'].transform('first')
)

linhas_vazias = df[df['preco_unitario'].isna()]
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(linhas_vazias)

,compra_id,quantidade_assentos,posicoes_assentos,origem,destino,preco_unitario,data_partida
178,C-000367,2,NaN,São Paulo (Tietê),NaN,NaN,NaN

In [13]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df)

,compra_id,quantidade_assentos,posicoes_assentos,origem,destino,preco_unitario,data_partida
0,C-000395,3,"9A, 11A, 15B",São Paulo (Tietê),Salvador (BA),270.97,2024/07/13
1,C-000270,2,"18A, 17B",São Paulo (Tietê),Curitiba (PR),114.81,2024-06-23 07:30
2,C-000094,3,"19B, 17B, 3A",São Paulo (Tietê),Porto Alegre (RS),221.01,2024-10-01 23:45
3,C-000123,4,"16B, 17A, 9B, 3B",São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
4,C-000308,2,"5B, 10A",São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
5,C-000365,2,"10B, 21B",São Paulo (Tietê),Rio de Janeiro (RJ),97.45,2024-01-13 22:30
6,C-000208,4,"20A, 21B, 2A, 3A",São Paulo (Tietê),Brasília (DF),185.15,2024-03-12 15:30
7,C-000359,2,"21B, 18A",São Paulo (Tietê),Curitiba (PR),108.82,2024-04-20 23:45
8,C-000068,1,3A,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
9,C-000451,3,"12A, 10A, 3B",São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
10,C-000092,1,5B,São Paulo (Tietê),Florianópolis (SC),172.06,2024-12-14 13:00
11,C-000086,2,"6A, 3B",São Paulo (Tietê),Florianópolis (SC),210.34,2024-12-15 09:00
12,C-000131,2,"18A, 16A",São Paulo (Tietê),Recife (PE),332.34,2024-11-07 20:00
13,C-000020,2,"2B, 21B",São Paulo (Tietê),Brasília (DF),169.85,2024-05-14 20:00
14,C-000283,2,"7B, 14B",São Paulo (Tietê),Brasília (DF),189.18,2024-10-26 07:30
15,C-000421,1,15A,São Paulo (Tietê),Curitiba (PR),108.82,2024-04-20 23:45
16,C-000295,1,14B,São Paulo (Tietê),Goiânia (GO),173.97,2024-03-19 07:30
17,C-000164,1,3A,São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
18,C-000247,4,"16B, 3B, 7B, 1B",São Paulo (Tietê),Curitiba (PR),121.57,2024-08-04 18:00
19,C-000453,1,15B,São Paulo (Tietê),Fortaleza (CE),350.00,2024-04-27 11:00
20,C-000401,4,"4A, 7B, 20B, 13B",São Paulo (Tietê),Brasília (DF),153.55,2024-05-06 11:00
21,C-000417,4,"12B, 6B, 2A, 6A",São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
22,C-000439,2,"8B, 7B",São Paulo (Tietê),Brasília (DF),184.86,2024-10-14 09:00
23,C-000327,1,16A,São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
24,C-000166,1,8B,São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
25,C-000399,1,3A,São Paulo (Tietê),Recife (PE),301.69,2024-11-21 18:00
26,C-000228,2,"7A, 8A",São Paulo (Tietê),Fortaleza (CE),342.57,2024-01-17 23:45
27,C-000111,1,13B,São Paulo (Tietê),Florianópolis (SC),195.42,2024-11-24 13:00
28,C-000215,1,4A,São Paulo (Tietê),Porto Alegre (RS),198.63,2024-03-04 11:00
29,C-000015,1,8B,São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
30,C-000240,1,7B,São Paulo (Tietê),Curitiba (PR),104.13,2024-12-23 07:30
31,C-000146,5,"19B, 12B, 13A, 16B, 10B",São Paulo (Tietê),Brasília (DF),195.46,2024-08-07 06:00
32,C-000072,2,"9A, 2A",São Paulo (Tietê),Porto Alegre (RS),221.01,2024-10-01 23:45
33,C-000450,2,"2A, 4B",São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
34,C-000112,1,15B,São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
35,C-000115,1,13B,São Paulo (Tietê),Fortaleza (CE),342.57,2024-01-17 23:45
36,C-000432,1,16A,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
37,C-000304,1,12A,São Paulo (Tietê),Florianópolis (SC),205.05,NaN
38,C-000446,1,13A,São Paulo (Tietê),Recife (PE),323.13,2024-03-28 13:00
39,C-000237,2,"19B, 14A",São Paulo (Tietê),Salvador (BA),270.99,2024-04-29 15:30
40,C-000223,1,20A,São Paulo (Tietê),Brasília (DF),184.86,2024-10-14 09:00
41,C-000333,1,17A,São Paulo (Tietê),Florianópolis (SC),205.05,2024-05-16 06:00
42,C-000487,1,NaN,São Paulo (Tietê),Florianópolis (SC),172.06,2024-12-14 13:00
43,C-000231,2,"12A, 4B",São Paulo (Tietê),Recife (PE),290.60,2024-09-30 22:30
44,C-000153,1,2B,São Paulo (Tietê),Curitiba (PR),114.81,2024-06-23 07:30
45,C-000217,1,10A,São Paulo (Tietê),Curitiba (PR),116.38,2024-03-20 15:30
46,C-000085,1,7B,São Paulo (Tietê),Goiânia (GO),147.41,2024-11-17 18:00
47,C-000389,2,"12B, 16B",São Paulo (Tietê),Porto Alegre (RS),216.61,2024-08-23 15:30
48,C-000078,2,"4B, 11A",São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
49,C-000203,4,"5A, 19B, 13A, 4A",São Paulo (Tietê),Florianópolis (SC),172.06,NaN
50,C-000235,3,"9A, 3B, 16A",São Paulo (Tietê),Brasília (DF),185.15,2024-03-12 15:30
51,C-000488,1,13A,São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-03-12 06:00
52,C-000383,2,"8A, 21B",São Paulo (Tietê),Florianópolis (SC),172.06,NaN
53,C-000182,2,"11A, 9A",São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-03-12 06:00
54,C-000469,2,"16B, 11A",São Paulo (Tietê),Porto Alegre (RS),202.74,NaN
55,C-000379,1,2B,São Paulo (Tietê),Porto Alegre (RS),211.83,2024-07-12 07:30
56,C-000294,1,21B,São Paulo (Tietê),Fortaleza (CE),342.57,2024-01-17 23:45
57,C-000047,2,"19B, 1B",São Paulo (Tietê),Recife (PE),300.08,2024-05-05 11:00
58,C-000445,2,"5B, 12B",São Paulo (Tietê),Belo Horizonte (MG),133.69,NaN
59,C-000172,2,"9A, 13B",São Paulo (Tietê),Recife (PE),300.08,2024-05-05 11:00
60,C-000475,2,"7B, 7A",São Paulo (Tietê),Salvador (BA),279.80,2024-08-20 11:00
61,C-000254,1,11A,São Paulo (Tietê),Belo Horizonte (MG),133.69,2024-04-21 11:00
62,C-000477,1,9A,São Paulo (Tietê),Recife (PE),332.34,2024-11-07 20:00
63,C-000079,1,15B,São Paulo (Tietê),Florianópolis (SC),202.19,2024-02-28 18:00
64,C-000008,2,"20A, 14B",São Paulo (Tietê),Salvador (BA),264.13,2024-11-21 13:00
65,C-000027,4,"8B, 6A, 14A, 16B",São Paulo (Tietê),Rio de Janeiro (RJ),87.93,2024-05-20 07:30
66,C-000019,2,"12A, 14B",São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
67,C-000193,5,"8B, 16A, 19A, 5B, 13A",São Paulo (Tietê),Florianópolis (SC),187.22,2024-10-10 15:30
68,C-000189,2,"12B, 20B",São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
69,C-000222,2,"11A, 1B",São Paulo (Tietê),Fortaleza (CE),329.20,2024-02-03 18:00
70,C-000138,3,"12A, 10A, 20B",São Paulo (Tietê),Fortaleza (CE),329.20,2024-02-03 18:00
71,C-000106,2,"12A, 10B",São Paulo (Tietê),Brasília (DF),185.15,2024-03-12 15:30
72,C-000433,2,"9A, 6B",São Paulo (Tietê),Florianópolis (SC),210.34,2024-12-15 09:00
73,C-000255,1,3B,São Paulo (Tietê),Florianópolis (SC),205.05,2024-05-16 06:00
74,C-000393,3,"7B, 2A, 7A",São Paulo (Tietê),Florianópolis (SC),210.34,2024-12-15 09:00
75,C-000018,3,"14A, 7A, 4A",São Paulo (Tietê),Salvador (BA),307.78,2024-05-22 15:30
76,C-000016,2,"7B, 18A",São Paulo (Tietê),Recife (PE),301.69,2024-11-21 18:00
77,C-000310,2,"4A, 7B",São Paulo (Tietê),Porto Alegre (RS),221.01,2024-10-01 23:45
78,C-000324,2,"13B, 11A",São Paulo (Tietê),Florianópolis (SC),188.92,2024-10-01 20:00
79,C-000466,5,"11A, 12A, 9A, 6B, 3B",São Paulo (Tietê),Fortaleza (CE),342.57,2024-01-17 23:45
80,C-000344,1,17A,São Paulo (Tietê),Porto Alegre (RS),211.83,2024-07-12 07:30
81,C-000185,1,13A,São Paulo (Tietê),Brasília (DF),169.85,2024-05-14 20:00
82,C-000414,3,"5B, 11B, 13A",São Paulo (Tietê),Porto Alegre (RS),198.63,2024-03-04 11:00
83,C-000212,1,19A,São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
84,C-000233,3,"1A, 10B, 20B",São Paulo (Tietê),Belo Horizonte (MG),103.01,NaN
85,C-000481,2,"4B, 1A",São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
86,C-000246,1,8A,São Paulo (Tietê),Belo Horizonte (MG),121.51,2024-04-29 22:30
87,C-000242,2,"6A, 15B",São Paulo (Tietê),Brasília (DF),189.18,2024-10-26 07:30
88,C-000499,3,"7B, 6B, 14A",São Paulo (Tietê),Goiânia (GO),155.36,2024-03-22 18:00
89,C-000293,3,"16B, 6A, 6B",São Paulo (Tietê),Porto Alegre (RS),225.64,2024-05-30 13:00
90,C-000209,2,"13A, 10A",São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
91,C-000467,4,"14B, 15A, 11B, 21A",São Paulo (Tietê),Goiânia (GO),164.97,2024-12-14 23:45
92,C-000158,2,"2B, 6B",São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
93,C-000474,1,12A,São Paulo (Tietê),Belo Horizonte (MG),103.05,2024-01-14 20:00
94,C-000118,5,"12A, 8A, 21B, 3A, 2A",São Paulo (Tietê),Belo Horizonte (MG),133.69,2024-04-21 11:00
95,C-000322,2,NaN,São Paulo (Tietê),Belo Horizonte (MG),103.05,2024-01-14 20:00
96,C-000033,4,"21A, 19B, 2B, 12A",São Paulo (Tietê),Porto Alegre (RS),225.64,2024-05-30 13:00
97,C-000194,4,"17B, 5A, 3A, 9B",São Paulo (Tietê),Porto Alegre (RS),211.83,2024-07-12 07:30
98,C-000076,1,19A,São Paulo (Tietê),Goiânia (GO),173.97,2024-03-19 07:30
99,C-000025,1,NaN,São Paulo (Tietê),Belo Horizonte (MG),118.14,2024-11-04 11:00
100,C-000040,4,"7B, 11A, 8B, 9A",São Paulo (Tietê),Fortaleza (CE),350.00,2024-04-27 11:00
101,C-000330,1,17B,São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
102,C-000066,0,8A,São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
103,C-000404,2,"3B, 13A",São Paulo (Tietê),Fortaleza (CE),350.00,2024-04-27 11:00
104,C-000276,1,10B,São Paulo (Tietê),Brasília (DF),195.86,2024-05-15 18:00
105,C-000326,3,NaN,São Paulo (Tietê),Belo Horizonte (MG),133.69,2024-04-21 11:00
106,C-000303,1,16B,São Paulo (Tietê),Curitiba (PR),101.30,2024-03-22 07:30
107,C-000074,2,NaN,São Paulo (Tietê),Goiânia (GO),173.97,2024-03-19 07:30
108,C-000346,1,7A,São Paulo (Tietê),Florianópolis (SC),205.05,2024-05-16 06:00
109,C-000102,2,"8B, 3B",São Paulo (Tietê),Brasília (DF),153.55,2024-05-06 11:00
110,C-000291,1,18B,São Paulo (Tietê),Salvador (BA),270.99,2024-04-29 15:30
111,C-000409,2,"14A, 5A",São Paulo (Tietê),Brasília (DF),195.86,2024-05-15 18:00
112,C-000133,1,8B,São Paulo (Tietê),Recife (PE),332.34,2024-11-07 20:00
113,C-000090,2,"3A, 16A",São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
114,C-000280,4,"13A, 1A, 7B, 6B",São Paulo (Tietê),Recife (PE),322.95,2024-03-24 15:30
115,C-000496,2,"8A, 7B",São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
116,C-000341,2,"9A, 16B",São Paulo (Tietê),Brasília (DF),173.09,2024-03-14 23:45
117,C-000472,3,"14A, 13B, 5A",São Paulo (Tietê),Brasília (DF),185.15,2024-03-12 15:30
118,C-000177,2,"9B, 6B",São Paulo (Tietê),Florianópolis (SC),188.92,NaN
119,C-000312,1,3A,São Paulo (Tietê),Fortaleza (CE),350.00,2024-04-27 11:00
120,C-000360,3,"6A, 9A, 3A",São Paulo (Tietê),Curitiba (PR),104.13,2024-12-23 07:30
121,C-000009,4,"7A, 10B, 13B, 21B",São Paulo (Tietê),Porto Alegre (RS),225.64,2024-05-30 13:00
122,C-000211,1,13B,São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
123,C-000150,2,"12B, 4B",São Paulo (Tietê),Recife (PE),301.69,2024-11-21 18:00
124,C-000380,1,18B,São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
125,C-000105,1,1B,São Paulo (Tietê),Brasília (DF),189.18,2024-10-26 07:30
126,C-000249,3,"21B, 8B, 9A",São Paulo (Tietê),Belo Horizonte (MG),102.96,2024-09-15 18:00
127,C-000054,1,16B,São Paulo (Tietê),Salvador (BA),264.13,2024-11-21 13:00
128,C-000070,2,"18B, 12A",São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
129,C-000278,2,"16A, 20A",São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
130,C-000410,1,18A,São Paulo (Tietê),Belo Horizonte (MG),103.01,2024-10-14 23:45
131,C-000077,1,3A,São Paulo (Tietê),Porto Alegre (RS),221.66,2024-02-10 06:00
132,C-000201,1,17B,São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-02-22 06:00
133,C-000429,1,15B,São Paulo (Tietê),Goiânia (GO),174.63,2024-08-04 20:00
134,C-000352,4,"19A, 2B, 18A, 16B",São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
135,C-000266,1,5A,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
136,C-000299,3,"19A, 17B, 18A",São Paulo (Tietê),Belo Horizonte (MG),118.14,2024-11-04 11:00
137,C-000199,2,"11B, 7A",São Paulo (Tietê),Brasília (DF),185.15,2024-03-12 15:30
138,C-000101,1,9A,São Paulo (Tietê),Belo Horizonte (MG),103.05,2024-01-14 20:00
139,C-000323,2,"11A, 13A",São Paulo (Tietê),Salvador (BA),307.78,2024-05-22 15:30
140,C-000249,3,"21B, 8B, 9A",São Paulo (Tietê),Belo Horizonte (MG),102.96,2024-09-15 18:00
141,C-000279,1,10A,São Paulo (Tietê),Recife (PE),332.34,2024-11-07 20:00
142,C-000213,1,13B,São Paulo (Tietê),Belo Horizonte (MG),121.51,2024-04-29 22:30
143,C-000056,2,"13A, 20A",São Paulo (Tietê),Curitiba (PR),93.82,2024-04-20 23:45
144,C-000268,4,"17A, 3A, 3B, 15B",São Paulo (Tietê),Brasília (DF),195.86,2024-05-15 18:00
145,C-000055,2,"4B, 3A",São Paulo (Tietê),Brasília (DF),195.46,2024-08-07 06:00
146,C-000250,3,"21B, 1A, 10B",São Paulo (Tietê),Fortaleza (CE),338.27,2024-06-10 15:30
147,C-000494,1,21A,São Paulo (Tietê),Porto Alegre (RS),211.83,2024-07-12 07:30
148,C-000486,4,"6B, 17A, 2A, 16B",São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-03-12 06:00
149,C-000216,2,NaN,São Paulo (Tietê),Brasília (DF),185.15,2024-03-12 15:30
150,C-000072,2,"9A, 2A",São Paulo (Tietê),Porto Alegre (RS),221.01,2024-10-01 23:45
151,C-000319,4,"21A, 7A, 12A, 18A",São Paulo (Tietê),Goiânia (GO),155.36,2024-03-22 18:00
152,C-000281,1,NaN,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
153,C-000024,1,8B,São Paulo (Tietê),Porto Alegre (RS),198.63,2024-03-04 11:00
154,C-000300,1,1B,São Paulo (Tietê),Recife (PE),290.60,2024-09-30 22:30
155,C-000230,1,16A,São Paulo (Tietê),Porto Alegre (RS),216.61,2024-08-23 15:30
156,C-000022,1,7A,São Paulo (Tietê),Curitiba (PR),101.30,2024-03-22 07:30
157,C-000214,1,15B,São Paulo (Tietê),Goiânia (GO),173.97,2024-03-19 07:30
158,C-000196,3,"10B, 11A, 21A",São Paulo (Tietê),Recife (PE),332.34,2024-11-07 20:00
159,C-000325,1,8A,São Paulo (Tietê),Brasília (DF),153.55,2024-05-06 11:00
160,C-000110,2,NaN,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
161,C-000452,1,NaN,São Paulo (Tietê),Florianópolis (SC),210.34,2024-12-15 09:00
162,C-000122,3,"6B, 12A, 4B",São Paulo (Tietê),Curitiba (PR),104.13,2024-12-23 07:30
163,C-000482,1,17A,São Paulo (Tietê),Porto Alegre (RS),241.98,NaN
164,C-000443,1,11B,São Paulo (Tietê),Curitiba (PR),101.30,2024-03-22 07:30
165,C-000143,1,14B,São Paulo (Tietê),Belo Horizonte (MG),103.01,2024-10-14 23:45
166,C-000220,5,"11A, 15A, 9B, 16A, 7A",São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
167,C-000206,2,"9B, 12B",São Paulo (Tietê),Belo Horizonte (MG),118.14,2024-11-04 11:00
168,C-000437,1,4B,São Paulo (Tietê),Fortaleza (CE),350.00,2024-04-27 11:00
169,C-000473,1,NaN,São Paulo (Tietê),Recife (PE),290.60,2024-09-30 22:30
170,C-000302,3,"14A, 4B, 16B",São Paulo (Tietê),Goiânia (GO),164.97,2024-12-14 23:45
171,C-000305,1,6A,São Paulo (Tietê),Fortaleza (CE),335.48,2024-07-24 11:00
172,C-000264,3,"11B, 19B, 20A",São Paulo (Tietê),Curitiba (PR),104.13,2024-12-23 07:30
173,C-000021,1,11B,São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
174,C-000460,2,"16A, 7B",São Paulo (Tietê),Florianópolis (SC),205.05,2024-05-16 06:00
175,C-000355,3,"18B, 8B, 4A",São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
176,C-000002,3,NaN,São Paulo (Tietê),Recife (PE),300.08,2024-05-05 11:00
177,C-000407,1,11B,São Paulo (Tietê),Curitiba (PR),134.71,2024-05-22 15:30
178,C-000367,2,NaN,São Paulo (Tietê),NaN,NaN,NaN
179,C-000274,1,18B,São Paulo (Tietê),Porto Alegre (RS),225.64,2024-05-30 13:00
180,C-000117,1,19B,São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
181,C-000336,4,"17A, 7B, 8B, 5A",São Paulo (Tietê),Fortaleza (CE),335.48,2024-07-24 11:00
182,C-000221,3,"5A, 11B, 16B",São Paulo (Tietê),Brasília (DF),153.55,2024-05-06 11:00
183,C-000135,3,"14B, 15A, 16A",São Paulo (Tietê),Salvador (BA),307.78,2024-05-22 15:30
184,C-000043,2,"19A, 4A",São Paulo (Tietê),Goiânia (GO),164.97,2024-12-14 23:45
185,C-000071,1,9A,São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
186,C-000403,3,"19B, 8A, 4B",São Paulo (Tietê),Curitiba (PR),134.71,2024-05-22 15:30
187,C-000145,2,NaN,São Paulo (Tietê),Brasília (DF),195.86,2024-05-15 18:00
188,C-000370,1,1B,São Paulo (Tietê),Brasília (DF),195.86,2024-05-15 18:00
189,C-000413,1,21A,São Paulo (Tietê),Fortaleza (CE),317.82,2024-05-17 20:00
190,C-000088,2,"8A, 7A",São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
191,C-000347,3,NaN,São Paulo (Tietê),Porto Alegre (RS),221.66,2024-02-10 06:00
192,C-000234,2,"9A, 20B",são paulo (tietê),Curitiba (PR),121.57,2024-08-04 18:00
193,C-000039,2,"19A, 17B",São Paulo (Tietê),Brasília (DF),189.18,2024-10-26 07:30
194,C-000165,1,15A,São Paulo (Tietê),Porto Alegre (RS),241.98,2024-01-23 23:45
195,C-000362,1,20B,São Paulo (Tietê),Goiânia (GO),164.97,2024-12-14 23:45
196,C-000120,2,"5A, 8A",São Paulo (Tietê),Curitiba (PR),114.81,2024-06-23 07:30
197,C-000337,1,5A,São Paulo (Tietê),Curitiba (PR),108.82,2024-04-20 23:45
198,C-000034,1,17A,São Paulo (Tietê),Belo Horizonte (MG),121.51,2024-04-29 22:30
199,C-000464,1,20B,São Paulo (Tietê),Porto Alegre (RS),202.74,NaN
200,C-000419,2,"15B, 14B",São Paulo (Tietê),Curitiba (PR),114.81,2024-06-23 07:30
201,C-000375,0,8B,São Paulo (Tietê),Recife (PE),290.60,2024-09-30 22:30
202,C-000471,1,16A,São Paulo (Tietê),Recife (PE),301.69,NaN
203,C-000169,2,"10A, 5B",São Paulo (Tietê),Salvador (BA),270.99,2024-04-29 15:30
204,C-000045,4,"3A, 8B, 12B, 10A",São Paulo (Tietê),Curitiba (PR),114.81,23/06/2024
205,C-000152,1,21B,São Paulo (Tietê),Porto Alegre (RS),221.01,2024-10-01 23:45
206,C-000432,1,16A,São Paulo (Tietê),Brasília (DF),174.22,2024-10-02 22:30
207,C-000396,2,"18A, 14B",São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-03-12 06:00
208,C-000476,1,21B,São Paulo (Tietê),Florianópolis (SC),195.42,2024-11-24 13:00
209,C-000003,1,6A,São Paulo (Tietê),Curitiba (PR),108.82,NaN
210,C-000200,2,"9B, 16B",São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
211,C-000387,1,7B,São Paulo (Tietê),Belo Horizonte (MG),103.05,2024-01-14 20:00
212,C-000252,1,7A,São Paulo (Tietê),Curitiba (PR),114.81,NaN
213,C-000098,3,"12B, 21A, 11B",São Paulo (Tietê),Salvador (BA),307.78,2024-05-22 15:30
214,C-000232,4,"7A, 10A, 16A, 15A",São Paulo (Tietê),Goiânia (GO),174.63,NaN
215,C-000424,2,"18B, 14B",São Paulo (Tietê),Rio de Janeiro (RJ),112.85,2024-04-24 18:00
216,C-000087,2,"12B, 3B",São Paulo (Tietê),Recife (PE),323.13,NaN
217,C-000434,1,11B,São Paulo (Tietê),Goiânia (GO),174.63,2024-08-04 20:00
218,C-000272,3,"3B, 12A, 13B",São Paulo (Tietê),Brasília (DF),195.46,2024-08-07 06:00
219,C-000258,4,"2A, 14B, 20B, 1B",São Paulo (Tietê),Salvador (BA),270.99,2024-04-29 15:30
220,C-000405,3,"19A, 17B, 7B",São Paulo (Tietê),Recife (PE),300.08,2024-05-05 11:00
221,C-000314,2,"8B, 12A",São Paulo (Tietê),Recife (PE),301.69,2024-11-21 18:00
222,C-000385,1,15A,São Paulo (Tietê),Brasília (DF),195.46,2024-08-07 06:00
223,C-000026,1,19B,São Paulo (Tietê),Curitiba (PR),133.63,2024-01-04 15:30
224,C-000461,1,4B,São Paulo (Tietê),Salvador (BA),307.78,2024-05-22 15:30
225,C-000064,1,2A,São Paulo (Tietê),Curitiba (PR),101.30,2024-03-22 07:30
226,C-000179,1,12B,São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
227,C-000416,1,8B,São Paulo (Tietê),Porto Alegre (RS),216.61,2024-08-23 15:30
228,C-000239,1,NaN,São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-03-12 06:00
229,C-000340,2,"2A, 14A",São Paulo (Tietê),Porto Alegre (RS),216.61,2024-08-23 15:30
230,C-000134,1,NaN,São Paulo (Tietê),Belo Horizonte (MG),103.01,2024-10-14 23:45
231,C-000256,1,14A,São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
232,C-000285,1,2B,São Paulo (Tietê),Curitiba (PR),108.82,2024-04-20 23:45
233,C-000465,3,"3B, 6A, 9A",São Paulo (Tietê),Goiânia (GO),152.81,2024-11-01 22:30
234,C-000053,1,5A,São Paulo (Tietê),Rio de Janeiro (RJ),97.45,2024-01-13 22:30
235,C-000028,1,13B,São Paulo (Tietê),Florianópolis (SC),187.22,2024-10-10 15:30
236,C-000335,1,11A,São Paulo (Tietê),Recife (PE),322.95,2024-03-24 15:30
237,C-000005,4,"10B, 8B, 2B, 19A",São Paulo (Tietê),Curitiba (PR),104.13,2024-12-23 07:30
238,C-000296,2,"18A, 19B",São Paulo (Tietê),Florianópolis (SC),195.42,2024-11-24 13:00
239,C-000126,1,14B,São Paulo (Tietê),Rio de Janeiro (RJ),86.49,2024-02-22 06:00
240,C-000384,1,3B,São Paulo (Tietê),Florianópolis (SC),188.92,01/10/2024
241,C-000493,2,"19A, 7B",São Paulo (Tietê),Rio de Janeiro (RJ),87.93,2024-05-20 07:30
242,C-000142,1,1B,São Paulo (Tietê),Florianópolis (SC),173.40,2024-01-06 07:30
243,C-000149,1,16B,São Paulo (Tietê),Porto Alegre (RS),198.63,2024-03-04 11:00
244,C-000265,1,18B,São Paulo (Tietê),Salvador (BA),275.62,2024-02-21 09:00
245,C-000462,1,13B,São Paulo (Tietê),Porto Alegre (RS),211.83,2024-07-12 07:30
246,C-000364,2,"6B, 10B",São Paulo (Tietê),Salvador (BA),270.97,2024-07-13 15:30
247,C-000084,3,"21B, 11B, 16A",São Paulo (Tietê),Goiânia (GO),173.97,2024-03-19 07:30
248,C-000061,5,"6A, 9A, 6B, 7A, 14B",São Paulo (Tietê),Brasília (DF),169.85,2024-05-14 20:00

In [14]:
# 4. Tratamento da coluna data_partida
#  Converte a coluna 'data_partida' para datetime YYYY-MM-DD HH:mm e deixa os registros inválidos como NaT (Not a Time) 
data_convertida = pd.to_datetime(df['data_partida'], format='%Y-%m-%d %H:%M', errors='coerce')

df['data_partida'] = data_convertida.dt.strftime('%Y-%m-%d %H:%M')

# Preenche os NaNs buscando a primeira data válida para a mesma combinação de 'destino' e 'preco_unitario'
df['data_partida'] = df['data_partida'].fillna(
    df.groupby(['destino', 'preco_unitario'])['data_partida'].transform('first')
)

linhas_vazias = df[df['data_partida'].isna()]
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(linhas_vazias)

,compra_id,quantidade_assentos,posicoes_assentos,origem,destino,preco_unitario,data_partida
54,C-000469,2,"16B, 11A",São Paulo (Tietê),Porto Alegre (RS),202.74,NaN
178,C-000367,2,NaN,São Paulo (Tietê),NaN,NaN,NaN
199,C-000464,1,20B,São Paulo (Tietê),Porto Alegre (RS),202.74,NaN

In [1]:
linhas_vazias = df[df['quantidade_assentos'] == 0]
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(linhas_vazias)

NameError: name 'df' is not defined

In [48]:
df.isnull().sum()

compra_id               0
quantidade_assentos     0
posicoes_assentos      31
origem                  0
destino                 1
preco_unitario          1
data_partida            3
dtype: int64

In [ ]:
# Após o tratamento até aqui, vamos manter os dados das vendas em que não houve escolha de assento (pode ocorrer dessa escolha não ter sido feita ou ignorada). Mas vamos dropar as demais linhas que não pudemos identificar.
# Ademais, vamos dropar as linhas que apresentem duplicatas exatas em todos os campos, pois segundo nossas regras de preenchimento, há forte indício que são registros duplicados de uma mesma venda.
# Após os drops, vou converter a coluna data para datetime.

df.drop(index=[54, 178, 199], inplace=True)
df.drop_duplicates(inplace=True)
df['data_partida'] = pd.to_datetime(df['data_partida'])
df['preco_unitario'] = pd.to_numeric(df['preco_unitario'], errors='coerce').round(2)

df.isnull().sum()

df.info()

<class 'pandas.DataFrame'>
Index: 497 entries, 0 to 510
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   compra_id            497 non-null    str
 1   quantidade_assentos  497 non-null    int64
 2   posicoes_assentos    467 non-null    str
 3   origem               497 non-null    str
 4   destino              497 non-null    str
 5   preco_unitario       497 non-null    float64
 6   data_partida         497 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(1), int64(1), str(4)
memory usage: 47.2 KB

In [55]:
# 5. Criação da coluna 'receita'
df['receita'] = (df['quantidade_assentos'] * df['preco_unitario'].astype(float)).round(2)

# Receita Mês a Mês 
receita_mensal = (
    df.groupby(df['data_partida'].dt.to_period('M'))['receita']
    .sum()
    .round(2)
    .reset_index()
)
receita_mensal.columns = ['Mês/Ano', 'Receita Total (R$)']
receita_mensal['Mês/Ano'] = receita_mensal['Mês/Ano'].astype(str)

print("=== RECEITA MÊS A MÊS ===")
display(receita_mensal)

# Receita por Destino (ordenada da maior para a menor receita)
receita_destino = (
    df.groupby('destino')['receita']
    .sum()
    .round(2)
    .sort_values(ascending=False)
    .reset_index()
)
receita_destino.columns = ['Destino', 'Receita Total (R$)']

print("\n=== RECEITA POR DESTINO ===")
display(receita_destino)

=== RECEITA MÊS A MÊS ===

    Mês/Ano  Receita Total (R$)
0   2024-01            15131.90
1   2024-02            11805.55
2   2024-03            25840.76
3   2024-04            19857.43
4   2024-05            39538.79
5   2024-06             8633.16
6   2024-07             9984.98
7   2024-08             8547.42
8   2024-09             4413.84
9   2024-10            14780.15
10  2024-11            16889.12
11  2024-12            11664.62

=== RECEITA POR DESTINO ===

               Destino  Receita Total (R$)
0       Fortaleza (CE)            29195.31
1          Recife (PE)            25985.12
2        Brasília (DF)            24977.83
3        Salvador (BA)            23982.92
4   Florianópolis (SC)            20135.07
5    Porto Alegre (RS)            16265.51
6        Curitiba (PR)            15871.84
7         Goiânia (GO)            13178.73
8  Belo Horizonte (MG)            10327.99
9  Rio de Janeiro (RJ)             7167.40

In [56]:
# Salva o DataFrame tratado em um arquivo CSV
df.to_csv('dados_passagens_limpo.csv', index=False, encoding='utf-8-sig', sep=';')